name = "Simply Exploration +"
author = "Sephiroth1993"
version = "1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9731b6ee0a2ef1c4c80abfc8dd74e1b27c33a859a7571f47f2e014f1a734bf20"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
