name = "Simply Exploration +"
author = "Sephiroth1993"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "548a73a6ba755184d8b2309e615bfa1df561bcc12c87e8714006c783b66c7d5b"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
