name = "Simply Exploration +"
author = "Sephiroth1993"
version = "1.8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20f457eb1ebd826b90d7db63145b5e8e6b07bef7d3441277bc840688480a5df8"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
