name = "Simply Exploration +"
author = "Sephiroth1993"
version = "1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9c7cd59d92673eb48db8a31b24643132626c0163f03ea5e8b82eacad29b339d"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
